### ISSUE TITLE
Mix knobs in mixer under linux

### ISSUE THREAD

**Issue by ContemporaryInsanity** [JerrySievert/CharredDesert#9]
Linux mint 19.1 xfce
Mix knobs do not render.
![image](https://user-images.githubusercontent.com/12547379/58100792-44437480-7bd6-11e9-848f-839d0d93b98e.png)

**Comment by JerrySievert** [comment]
odd, are those the only knobs you've seen not mixing?

**Comment by ContemporaryInsanity** [comment]
Yup, all knobs on all of your other modules render & work fine.

**Comment by JerrySievert** [comment]
issue was a casing issue for one letter of the asset.  I'll leave this open until a new build is pushed.

only shows up on linux due to case-sensitive filesystem.  most macOS users have case-insensitive filesystems due to some, er, historic software that doesn't handle a case-sensitive filesystem, and windows is on a per directory basis (as of April 2018 update).

**Comment by JerrySievert** [comment]
this should now be live - feel free to open the issue back up if there is still a problem after updating plugins.
